# Generated by Django 4.1 on 2024-01-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='publicado',
            new_name='publicada',
        ),
    ]
